import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Menu from "../components/Menu";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className="container mx-auto w-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu />

      <div className="flex flex-col place-items-center py-44 space-y-3">
        <h1 className="text-5xl font-bold">Ayo Mulai Voting</h1>
        <h2 className="text-lg bg-zinc-100 py-1 px-3">
          Web Voting No.1 di Indonesia
        </h2>
        <Image alt={"home"} src={"/assets/home.svg"} width={274} height={243} />
        <div className="space-x-10">
          <Button text="Buat Vote Baru" className="font-bold" />
          <Button text="Ikut Vote" type="secondary" className="font-bold" />
        </div>
      </div>

      <div>
        <p className="py-5 font-lg font-bold">Vote yang saya buat</p>
        <table className="table-auto w-full border border-zinc-100">
          <tr className="border-b border-zinc-100">
            <th className="p-5 text-left">No.</th>
            <th className="p-5 text-left">Judul</th>
            <th className="p-5 text-left">Kandidat</th>
            <th className="p-5 text-left">Kode</th>
            <th className="p-5 text-left">Mulai</th>
            <th className="p-5 text-left">Selesai</th>
            <th className="p-5 text-left"></th>
          </tr>
          <tbody>
            <tr>
              <td className="p-5 text-left">1</td>
              <td className="p-5 text-left">Judul Voting</td>
              <td className="p-5 text-left">Coffee vs Milk</td>
              <td className="p-5 text-left">CNJKSHCUI</td>
              <td className="p-5 text-left">26 March 2023 09:00</td>
              <td className="p-5 text-left">28 March 2023 23:59</td>
              <td className="p-5 text-left"></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
};

export default Home;
